// Generated by CoffeeScript 1.6.2
var Main, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Main = (function(_super) {
  var init, run;

  __extends(Main, _super);

  function Main() {
    _ref = Main.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  window.onload = function() {
    return init();
  };

  init = function() {
    this.page = {};
    this.page.main = new Terraforming();
    this.currentPage = page.main;
    Main.__super__.init.call(this, this.page, this.currentPage);
    return run();
  };

  run = function() {
    return Main.__super__.run.call(this);
  };

  return Main;

})(Engine);
