// Generated by CoffeeScript 1.6.2
var httpRequest, playerNames, userNames, writePage,
  _this = this;

userNames = ["iskwkn", "uwi", "sy", "R.Kuzumi", "b_head", "niwa", "hasi", "yhrin", "bells", "henteko", "jag"];

playerNames = ["todo takatora", "Wall Cult", "test", "kuzumi", "B_head:ColonizeAI", "TEST_A", "hasi", "yhrin", "yai", "henteko", "SettlerX"];

writePage = function(result) {
  var game, gameId, i, index, player, rank, rankName, replay, replayLink, text, _i;

  text = '<h2>Game</h2>\n  <table class=\'result\'>\n    <tr class=\'header\'>\n      <th>Game</th>\n      <th>Rank</th>\n      <th>Name</th>\n      <th>AI Name</th>\n      <th>Score</th>\n      <th>Replay</th>\n    </tr>';
  gameId = 0;
  for (index in result) {
    ++gameId;
    game = result[index];
    rank = [game.ranks.indexOf(1), game.ranks.indexOf(2), game.ranks.indexOf(3)];
    rankName = ['1st', '2nd', '3rd'];
    player = [];
    replay = game.file;
    replayLink = "<a href='" + (replay.substring(replay.indexOf('') + 1, replay.indexOf('.'))) + ".html'>replay</a>";
    for (i = _i = 0; _i < 3; i = ++_i) {
      player[i] = {};
      player[i].name = userNames[playerNames.indexOf(game.names[rank[i]])];
      player[i].aiName = game.names[rank[i]];
      player[i].score = game.scores[rank[i]];
    }
    text += "<tr>\n  <td rowspan=\"3\">#" + gameId + "</td>\n  <td>1st</td>\n  <td class='name'>" + player[0].name + "</td>\n  <td class='name'>" + player[0].aiName + "</td>\n  <td>" + player[0].score + "</td>\n  <td rowspan=\"3\">" + replayLink + "</td>\n</tr>\n<tr>\n  <td>2nd</td>\n  <td class='name'>" + player[1].name + "</td>\n  <td class='name'>" + player[1].aiName + "</td>\n  <td>" + player[1].score + "</td>\n</tr>\n<tr>\n  <td>3rd</td>\n  <td class='name'>" + player[2].name + "</td>\n  <td class='name'>" + player[2].aiName + "</td>\n  <td>" + player[2].score + "</td>\n</tr>";
  }
  text += "</table>";
  return document.getElementById('game').innerHTML = text;
};

httpRequest = new XMLHttpRequest();

httpRequest.open('GET', 'applet/replay/result.json', true);

httpRequest.addEventListener("load", (function(event) {
  var result;

  if (httpRequest.readyState === 4) {
    result = JSON.parse(httpRequest.responseText);
    httpRequest = null;
    return writePage(result);
  }
}));

httpRequest.send(null);
