// Generated by CoffeeScript 1.7.1
(function() {
  var menu;

  menu = '  <ul>\n    <li><a href="index.html">INFORMATION</a></li>\n    <li><a href="documents.html">DOCUMENTS</a></li>\n    <li><a href="download.html">DOWNLOAD</a></li>\n  </ul>\n  <div id=\'twitter\'>\n<a class="twitter-timeline" href="https://twitter.com/search?q=%23cedecai" data-widget-id="357200114659508224">#cedecai に関するツイート</a>\n<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?\'http\':\'https\';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>\n</div>';

  document.write(menu);

}).call(this);
