// Generated by CoffeeScript 1.7.1
$(document).ready(function() {
  var clickLink, innerLink;
  $('#top').load('./top.html');
  $('#screenshots').load('./screenshots.html');
  $('#game-rules').load('./game-rules.html');
  $('#play').load('./play.html');
  $('#contest-rules').load('./contest-rules.html');
  $('#links').load('./links.html');
  $(".fancybox").fancybox();
  innerLink = function(activeBox) {
    $('.box').hide();
    return $(activeBox).show(1, function() {
      return window.scrollTo(0, 0);
    });
  };
  $('ul#menu li').click(function() {
    var activeBox;
    activeBox = $(this).find('a').attr('href');
    return innerLink(activeBox);
  });
  $('a.expand').click(function() {
    return $('div.expand').slideToggle();
  });
  clickLink = function() {
    var hash;
    hash = window.location.hash;
    if (hash !== '') {
      return innerLink(hash);
    }
  };
  $(window).bind('hashchange', function() {
    return clickLink();
  });
  if (window.location.hash === '') {
    $('#top').fadeIn('slow');
    return $('ul#menu').hide(0, function() {
      return $('ul#menu').fadeIn('slow');
    });
  } else {
    return clickLink();
  }
});
