// Generated by CoffeeScript 1.7.1
$(document).ready(function() {
  var innerLink;
  $('#top').fadeIn();
  $('ul#menu').fadeIn();
  $('#game-rules').load('./game-rules.html');
  innerLink = function(activeBox) {
    $('.box').hide();
    return $(activeBox).fadeIn();
  };
  $('ul#menu li').click(function() {
    var activeBox;
    $('#description p').hide();
    $('#description h1').show();
    activeBox = $(this).find('a').attr('href');
    return innerLink(activeBox);
  });
  $('#description h1').click(function() {
    var activeBox;
    $('#description p').fadeIn();
    $('#description h1').hide();
    activeBox = $(this).find('a').attr('href');
    return innerLink(activeBox);
  });
  return $('a.expand').click(function() {
    return $('div.expand').slideToggle();
  });
});
